#!/bin/bash

# 定义要扫描的包名列表
packages=(
    "net.easyconn"
    "com.iflytek.autofly.avatar"
    "com.iflytek.autofly.map"
    "com.iflytek.cutefly.speechclient.hmi"
    "com.tencent.wecar.karaoke"
    "com.loostone.tuning"
    "com.tencent.wecarnavi"
    "com.tencent.wecarflow"
    "com.tencent.wecar"
    "com.tencent.mm"
    "com.ts.apa.activity"
    "com.visteon.launcher"
    "com.ts.cockpit.carplay"
    "com.ts.cockpit.dmsservice"
    "com.cdc.engineeringmode"
    "com.visteon.remote.ivi.log"
    "com.visteon.smartscene"
    "com.visteon.systemsettings"
    "com.android.systemui"
    "com.cdc.backgroundupdateprogram"
    "com.visteon.vtwox"
    "com.visteon.vehicle.service"
    "com.ts.cockpit.parking"
    "com.visteon.hvac"
    "com.aha.autocar.vehicle"
    "com.visteon.txzing.btphone"
    "com.visteon.txzing.ecall"
    "com.visteon.txzing.familytime"
    "com.kika.car.inputmethod"
    "com.visteon.txzing.media"
    "com.visteon.txzing.safe"
    "com.visteon.txzing.screensaver"
    "com.oneiotworld.aiot.jmc.uav789"
    "com.txzing.dragonfly"
    "com.visteon.txzing.accountcenter"
    "com.txznet.ai.handbook"
    "com.visteon.txzing.appstore"
    "com.txznet.txz"
    "com.ford.beyond"
    "com.android.visteon.p789systemservice"
    "com.android.ext.autoweather"
    "com.visteon.android.voicecontroller"
    "com.redstone.fota"
    "com.zhonghong.ota"
)

# 依次扫描每个包名
for package in "${packages[@]}"; do
    echo "正在扫描包: $package"
    ./drozer-tester.sh "$package"
    echo "包 $package 扫描完成"
done
